/**
 * Peer wire framing.
 *
 * These are the messages ma-stream never implemented, so nothing upstream pins their byte layout.
 * A wrong offset here does not throw — it requests the wrong bytes and the swarm quietly ignores
 * you, which looks identical to having no peers. So the fixtures are hand-computed rather than
 * generated by the same code under test.
 */

import { describe, expect, it } from "vitest";
import {
  Bitfield,
  BLOCK_SIZE,
  blocksFor,
  cancelFrame,
  frame,
  interestedFrame,
  keepAliveFrame,
  MSG_CANCEL,
  MSG_INTERESTED,
  MSG_REQUEST,
  parseBlockRequest,
  parseHave,
  parsePiece,
  requestFrame,
} from "../src/wire/messages.ts";
import { buildHandshake, generatePeerId } from "../src/wire/handshake.ts";
import { fromHex, toHex } from "../src/bytes.ts";
import { WireError } from "../src/wire/conn.ts";

describe("framing", () => {
  it("prefixes length including the id byte", () => {
    const empty = frame(MSG_INTERESTED);
    // <len=0001><id=2>
    expect(toHex(empty)).toBe("0000000102");
    expect(empty.length).toBe(5);
  });

  it("encodes a keep-alive as four zero bytes and no id", () => {
    expect(toHex(keepAliveFrame())).toBe("00000000");
  });

  it("matches the canonical interested message", () => {
    expect(toHex(interestedFrame())).toBe("0000000102");
  });
});

describe("request and cancel", () => {
  it("lays out index, begin and length as three big-endian uint32s", () => {
    const wire = requestFrame(1, BLOCK_SIZE, BLOCK_SIZE);
    // <len=0013><id=6><index=1><begin=0x4000><length=0x4000>
    expect(toHex(wire)).toBe("0000000d06" + "00000001" + "00004000" + "00004000");
    expect(wire.length).toBe(4 + 13);
  });

  it("differs from cancel only in the id", () => {
    const request = requestFrame(7, 32_768, BLOCK_SIZE);
    const cancel = cancelFrame(7, 32_768, BLOCK_SIZE);
    expect(request[4]).toBe(MSG_REQUEST);
    expect(cancel[4]).toBe(MSG_CANCEL);
    expect(toHex(request.subarray(5))).toBe(toHex(cancel.subarray(5)));
  });

  it("round-trips through its own parser", () => {
    const wire = requestFrame(1_054, 49_152, 8_192);
    expect(parseBlockRequest(wire.subarray(5))).toEqual({
      index: 1_054,
      begin: 49_152,
      length: 8_192,
    });
  });

  it("survives an index above 2^31, which a large torrent reaches", () => {
    const wire = requestFrame(3_000_000_000, 0, BLOCK_SIZE);
    // A signed read would come back negative here.
    expect(parseBlockRequest(wire.subarray(5)).index).toBe(3_000_000_000);
  });
});

describe("piece", () => {
  it("decodes header and block without copying the payload", () => {
    const payload = new Uint8Array(8 + 4);
    const view = new DataView(payload.buffer);
    view.setUint32(0, 42);
    view.setUint32(4, BLOCK_SIZE);
    payload.set([0xde, 0xad, 0xbe, 0xef], 8);

    const piece = parsePiece(payload);
    expect(piece.index).toBe(42);
    expect(piece.begin).toBe(BLOCK_SIZE);
    expect(toHex(piece.block)).toBe("deadbeef");
    // A view, so a 16 KiB block is not duplicated on the way through.
    expect(piece.block.buffer).toBe(payload.buffer);
  });

  it("rejects a truncated header rather than reading garbage offsets", () => {
    expect(() => parsePiece(new Uint8Array(7))).toThrow(WireError);
  });

  it("accepts a zero-length block, which is legal if useless", () => {
    const payload = new Uint8Array(8);
    expect(parsePiece(payload).block.length).toBe(0);
  });
});

describe("have", () => {
  it("reads a big-endian piece index", () => {
    const payload = new Uint8Array(4);
    new DataView(payload.buffer).setUint32(0, 1_054);
    expect(parseHave(payload)).toBe(1_054);
  });

  it("rejects a short payload", () => {
    expect(() => parseHave(new Uint8Array(3))).toThrow(WireError);
  });
});

describe("bitfield", () => {
  it("puts piece 0 in the high bit of the first byte", () => {
    // 0b10000000 -> piece 0 only. Reading this little-endian is the classic bug: it would report
    // piece 7 instead, so every request goes to a peer that does not have the piece.
    const field = Bitfield.fromPayload(new Uint8Array([0x80]), 8);
    expect(field.has(0)).toBe(true);
    expect(field.has(1)).toBe(false);
    expect(field.has(7)).toBe(false);
    expect(field.count).toBe(1);
  });

  it("reads the last piece of a byte", () => {
    const field = Bitfield.fromPayload(new Uint8Array([0x01]), 8);
    expect(field.has(7)).toBe(true);
    expect(field.has(0)).toBe(false);
  });

  it("spans byte boundaries", () => {
    // 0x00 0x80 -> piece 8
    const field = Bitfield.fromPayload(new Uint8Array([0x00, 0x80]), 16);
    expect(field.has(8)).toBe(true);
    expect(field.count).toBe(1);
  });

  it("ignores spare high bits in the final byte", () => {
    // 1055 pieces needs 132 bytes; the last 7 bits are padding and must never be reported.
    const bits = new Uint8Array(132).fill(0xff);
    const field = Bitfield.fromPayload(bits, 1_055);
    expect(field.count).toBe(1_055);
    expect(field.has(1_054)).toBe(true);
    expect(field.has(1_055)).toBe(false);
  });

  it("rejects a bitfield too short for the torrent", () => {
    expect(() => Bitfield.fromPayload(new Uint8Array(131), 1_055)).toThrow(WireError);
  });

  it("round-trips through set()", () => {
    const field = new Bitfield(1_055);
    field.set(0);
    field.set(1_054);
    expect(field.has(0)).toBe(true);
    expect(field.has(1_054)).toBe(true);
    expect(field.count).toBe(2);
    expect(Bitfield.full(1_055).count).toBe(1_055);
  });
});

describe("block planning", () => {
  it("splits a 256 KiB piece into 16 full blocks", () => {
    const blocks = blocksFor(262_144);
    expect(blocks.length).toBe(16);
    expect(blocks[0]).toEqual({ begin: 0, length: BLOCK_SIZE });
    expect(blocks[15]).toEqual({ begin: 15 * BLOCK_SIZE, length: BLOCK_SIZE });
  });

  it("shortens the final block of a ragged last piece", () => {
    const blocks = blocksFor(145_691); // Big Buck Bunny's last piece
    expect(blocks.length).toBe(9);
    expect(blocks.at(-1)).toEqual({ begin: 8 * BLOCK_SIZE, length: 14_619 });
    expect(blocks.reduce((sum, b) => sum + b.length, 0)).toBe(145_691);
  });

  it("covers every byte with no overlap", () => {
    for (const pieceLength of [1, BLOCK_SIZE, BLOCK_SIZE + 1, 262_144, 4_194_304]) {
      const blocks = blocksFor(pieceLength);
      let at = 0;
      for (const block of blocks) {
        expect(block.begin).toBe(at);
        at += block.length;
      }
      expect(at).toBe(pieceLength);
    }
  });
});

describe("handshake", () => {
  const infoHash = fromHex("dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c");

  it("builds the canonical 68 bytes", () => {
    const peerId = generatePeerId();
    const wire = buildHandshake(infoHash, peerId);
    expect(wire.length).toBe(68);
    expect(wire[0]).toBe(19);
    expect(new TextDecoder().decode(wire.subarray(1, 20))).toBe("BitTorrent protocol");
    expect(toHex(wire.subarray(28, 48))).toBe(toHex(infoHash));
    expect(toHex(wire.subarray(48, 68))).toBe(toHex(peerId));
  });

  it("advertises the extension protocol bit", () => {
    const wire = buildHandshake(infoHash, generatePeerId());
    // Reserved byte 5, bit 0x10 — BEP-10.
    expect(wire[20 + 5]! & 0x10).toBe(0x10);
  });

  it("advertises fast and DHT together in reserved byte 7", () => {
    const wire = buildHandshake(infoHash, generatePeerId());
    // BEP-6 fast (0x04) and BEP-5 DHT (0x01) share byte 7, so both must survive. An assignment
    // per bit instead of an or would silently drop one, and the loss is invisible on the wire.
    expect(wire[20 + 7]).toBe(0x05);
    // Nothing else is claimed.
    expect([...wire.subarray(20, 28)]).toEqual([0, 0, 0, 0, 0, 0x10, 0, 0x05]);
  });

  it("refuses a malformed infohash or peer id", () => {
    expect(() => buildHandshake(new Uint8Array(19), generatePeerId())).toThrow(WireError);
    expect(() => buildHandshake(infoHash, new Uint8Array(21))).toThrow(WireError);
  });

  it("generates a 20-byte printable peer id", () => {
    const peerId = generatePeerId();
    expect(peerId.length).toBe(20);
    expect(new TextDecoder().decode(peerId.subarray(0, 8))).toBe("-CL0001-");
    for (const byte of peerId.subarray(8)) {
      expect(byte).toBeGreaterThanOrEqual(0x30);
      expect(byte).toBeLessThan(0x7f);
    }
  });
});
